### PR TITLE
Initial database dump usage

### LINKED ISSUE #14: Database seeding script
We need to find out how to make this command work, since postgres image does not have wget installed:

docker exec -it api_postgres_1 bash -c "wget https://plezanje.info/storage/db_lite.sql && psql -U plezanjenet -f db_lite.sql"

.. or some other way to download the dump and run it inside the local container

+ update readme file accordingly

### PR DESCRIPTION
**Pull request by demshy**
Added db folder as mounted drive.
Added readme entry with scripts to curl the latest dump and run it on local postgres.
closes #14

### CODE REVIEW

**Comment by demshy** [comment]
You need to stop the container for the mount to take effect in order to test this:
`docker-compose stop`
`docker-compose up -d`

**Comment by salamca** [comment]
Crag table is empty. 
Route table has only one entry.

Cannot really test this properly cause FE inconsistent now...

**Comment by demshy** [comment]
We will create a new dump after the latest version is deployed and try again.

**Review by salamca — COMMENTED** [review]
olgud

**Review by salamca — APPROVED** [review]

**Pull request merged**
